// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: usertoken/proto/usertoken.proto

package orbli_micro_usertoken

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UsertokenService service

type UsertokenService interface {
	Create(ctx context.Context, in *Usertoken, opts ...client.CallOption) (*Usertoken, error)
	Read(ctx context.Context, in *Usertoken, opts ...client.CallOption) (*Usertoken, error)
	Delete(ctx context.Context, in *Usertoken, opts ...client.CallOption) (*Usertoken, error)
}

type usertokenService struct {
	c    client.Client
	name string
}

func NewUsertokenService(name string, c client.Client) UsertokenService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "orbli.micro.usertoken"
	}
	return &usertokenService{
		c:    c,
		name: name,
	}
}

func (c *usertokenService) Create(ctx context.Context, in *Usertoken, opts ...client.CallOption) (*Usertoken, error) {
	req := c.c.NewRequest(c.name, "UsertokenService.Create", in)
	out := new(Usertoken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usertokenService) Read(ctx context.Context, in *Usertoken, opts ...client.CallOption) (*Usertoken, error) {
	req := c.c.NewRequest(c.name, "UsertokenService.Read", in)
	out := new(Usertoken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usertokenService) Delete(ctx context.Context, in *Usertoken, opts ...client.CallOption) (*Usertoken, error) {
	req := c.c.NewRequest(c.name, "UsertokenService.Delete", in)
	out := new(Usertoken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UsertokenService service

type UsertokenServiceHandler interface {
	Create(context.Context, *Usertoken, *Usertoken) error
	Read(context.Context, *Usertoken, *Usertoken) error
	Delete(context.Context, *Usertoken, *Usertoken) error
}

func RegisterUsertokenServiceHandler(s server.Server, hdlr UsertokenServiceHandler, opts ...server.HandlerOption) error {
	type usertokenService interface {
		Create(ctx context.Context, in *Usertoken, out *Usertoken) error
		Read(ctx context.Context, in *Usertoken, out *Usertoken) error
		Delete(ctx context.Context, in *Usertoken, out *Usertoken) error
	}
	type UsertokenService struct {
		usertokenService
	}
	h := &usertokenServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UsertokenService{h}, opts...))
}

type usertokenServiceHandler struct {
	UsertokenServiceHandler
}

func (h *usertokenServiceHandler) Create(ctx context.Context, in *Usertoken, out *Usertoken) error {
	return h.UsertokenServiceHandler.Create(ctx, in, out)
}

func (h *usertokenServiceHandler) Read(ctx context.Context, in *Usertoken, out *Usertoken) error {
	return h.UsertokenServiceHandler.Read(ctx, in, out)
}

func (h *usertokenServiceHandler) Delete(ctx context.Context, in *Usertoken, out *Usertoken) error {
	return h.UsertokenServiceHandler.Delete(ctx, in, out)
}
