// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package orbli_micro_util_event

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Origin               string               `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Action               string               `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Message              string               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Event) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "orbli.micro.util.event.Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8d, 0x3d, 0x8e, 0x83, 0x30,
	0x10, 0x85, 0x65, 0x76, 0x61, 0x85, 0x91, 0xb6, 0x70, 0x81, 0x2c, 0x9a, 0xa0, 0x54, 0x54, 0x83,
	0x94, 0x34, 0xb9, 0x40, 0x2e, 0x80, 0x72, 0x01, 0x7e, 0x1c, 0x6b, 0x24, 0xcc, 0x20, 0x63, 0x72,
	0x99, 0x5c, 0x36, 0xc2, 0x0e, 0x49, 0xf9, 0xde, 0xfb, 0xe6, 0x1b, 0x9e, 0xa9, 0x87, 0x9a, 0x1c,
	0xcc, 0x96, 0x1c, 0x89, 0x9c, 0x6c, 0x37, 0x22, 0x18, 0xec, 0x2d, 0xc1, 0xea, 0x70, 0x04, 0xbf,
	0x16, 0x07, 0x4d, 0xa4, 0x47, 0x55, 0x7b, 0xaa, 0x5b, 0xef, 0xb5, 0x43, 0xa3, 0x16, 0xd7, 0x9a,
	0x39, 0x1c, 0x1e, 0x9f, 0x8c, 0xc7, 0xd7, 0x0d, 0x15, 0xff, 0x3c, 0xc2, 0x41, 0xb2, 0x92, 0x55,
	0x69, 0x13, 0xe1, 0x20, 0x2e, 0x3c, 0xfd, 0xc0, 0x32, 0x2a, 0x59, 0x95, 0x9d, 0x0a, 0x08, 0x3a,
	0xd8, 0x75, 0x70, 0xdb, 0x89, 0xe6, 0x0b, 0x8b, 0x9c, 0x27, 0x64, 0x51, 0xe3, 0x24, 0x7f, 0xbc,
	0xed, 0x9d, 0xb6, 0xbe, 0xed, 0x1d, 0xd2, 0x24, 0x7f, 0x43, 0x1f, 0x92, 0x90, 0xfc, 0xcf, 0xa8,
	0x65, 0x69, 0xb5, 0x92, 0xb1, 0x1f, 0xf6, 0xd8, 0x25, 0xfe, 0xd1, 0xf9, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x75, 0xe2, 0x0b, 0xa8, 0xec, 0x00, 0x00, 0x00,
}
